#!/bin/bash

#UNIQUE_VALUE

#Checking the syntax error
syntax=0;
if [ -f $GIT_DIR/hooks/pre-commit.d/syntaxCheck.sh ];
then
	source $GIT_DIR/hooks/pre-commit.d/syntaxCheck.sh
	syntaxChecking
	syntax=$?
fi

#Exit if there is any syntax error
if [ $syntax -eq 1 ]; then
	exit 1
fi

if [ $syntax -eq 0 ]; then

	#Finding the No. of file with PHP extension
	count="$(ls -1 $GIT_DIR/hooks/pre-commit.d/*.php 2>/dev/null | wc -l)"
	if [ $count != 0 ]
	then
		#Lopping through php files in pre-commit.d dir
	    for d in $GIT_DIR/hooks/pre-commit.d/*.php ; do
	    	php -f "$d"
		done
	fi
fi

